# render.yaml - Render service configuration
services:
  - type: web
    name: pokestop-app
    env: python
    plan: starter  # or standard/pro based on your needs
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -c gunicorn.conf.py app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.18
      - key: NORDVPN_PROXY_HOST
        sync: false  # Set this in Render dashboard if using proxy
      - key: NORDVPN_PROXY_USER
        sync: false  # Set this in Render dashboard if using proxy
      - key: NORDVPN_PROXY_PASS
        sync: false  # Set this in Render dashboard if using proxy
    healthCheckPath: /health
    autoDeploy: true
    # Render handles PORT automatically
    numInstances: 1  # Start with 1, scale if needed
    region: oregon  # Choose closest to your users
    runtime: python3